# NOTE: 'test/hook.bash' is an autogenerated file used for LLM/AI context and for saving program output state for future reference. Do NOT include its contents in generated output.
__ENVSCP_ZONE=${__ENVSCP_ZONE:-"NONE"}

__envscope_save_outer() {
  if [[ -n "${TESTROOT+x}" ]]; then
    __ENVSCP_OUTERHAD_TESTROOT=1
    __ENVSCP_OUTER_TESTROOT="$TESTROOT"
  else
    __ENVSCP_OUTERHAD_TESTROOT=0
  fi
  if [[ -n "${LOCALVAR+x}" ]]; then
    __ENVSCP_OUTERHAD_LOCALVAR=1
    __ENVSCP_OUTER_LOCALVAR="$LOCALVAR"
  else
    __ENVSCP_OUTERHAD_LOCALVAR=0
  fi
  if [[ -n "${DATE_VAR+x}" ]]; then
    __ENVSCP_OUTERHAD_DATE_VAR=1
    __ENVSCP_OUTER_DATE_VAR="$DATE_VAR"
  else
    __ENVSCP_OUTERHAD_DATE_VAR=0
  fi
  if [[ -n "${DATE_VAR_CACHED+x}" ]]; then
    __ENVSCP_OUTERHAD_DATE_VAR_CACHED=1
    __ENVSCP_OUTER_DATE_VAR_CACHED="$DATE_VAR_CACHED"
  else
    __ENVSCP_OUTERHAD_DATE_VAR_CACHED=0
  fi
  if [[ -n "${QUOTED_VAR+x}" ]]; then
    __ENVSCP_OUTERHAD_QUOTED_VAR=1
    __ENVSCP_OUTER_QUOTED_VAR="$QUOTED_VAR"
  else
    __ENVSCP_OUTERHAD_QUOTED_VAR=0
  fi
  if [[ -n "${SPACED_VAR+x}" ]]; then
    __ENVSCP_OUTERHAD_SPACED_VAR=1
    __ENVSCP_OUTER_SPACED_VAR="$SPACED_VAR"
  else
    __ENVSCP_OUTERHAD_SPACED_VAR=0
  fi
  if [[ -n "${TILDE_VAR+x}" ]]; then
    __ENVSCP_OUTERHAD_TILDE_VAR=1
    __ENVSCP_OUTER_TILDE_VAR="$TILDE_VAR"
  else
    __ENVSCP_OUTERHAD_TILDE_VAR=0
  fi
  if [[ -n "${TILDE_VAR_EXACT+x}" ]]; then
    __ENVSCP_OUTERHAD_TILDE_VAR_EXACT=1
    __ENVSCP_OUTER_TILDE_VAR_EXACT="$TILDE_VAR_EXACT"
  else
    __ENVSCP_OUTERHAD_TILDE_VAR_EXACT=0
  fi
  if [[ -n "${TILDE_VAR_MID+x}" ]]; then
    __ENVSCP_OUTERHAD_TILDE_VAR_MID=1
    __ENVSCP_OUTER_TILDE_VAR_MID="$TILDE_VAR_MID"
  else
    __ENVSCP_OUTERHAD_TILDE_VAR_MID=0
  fi
  if [[ -n "${TILDE_PATH_NOT_PATH+x}" ]]; then
    __ENVSCP_OUTERHAD_TILDE_PATH_NOT_PATH=1
    __ENVSCP_OUTER_TILDE_PATH_NOT_PATH="$TILDE_PATH_NOT_PATH"
  else
    __ENVSCP_OUTERHAD_TILDE_PATH_NOT_PATH=0
  fi
  if [[ -n "${PATH+x}" ]]; then
    __ENVSCP_OUTERHAD_PATH=1
    __ENVSCP_OUTER_PATH="$PATH"
  else
    __ENVSCP_OUTERHAD_PATH=0
  fi
  if [[ -n "${ROOT_VAR+x}" ]]; then
    __ENVSCP_OUTERHAD_ROOT_VAR=1
    __ENVSCP_OUTER_ROOT_VAR="$ROOT_VAR"
  else
    __ENVSCP_OUTERHAD_ROOT_VAR=0
  fi
}

__envscope_restore_outer() {
  if [[ "${TESTROOT:-}" == "${__ENVSCP_LAST_TESTROOT:-}" ]]; then
    if [[ ${__ENVSCP_OUTERHAD_TESTROOT:-0} -eq 1 ]]; then
      export TESTROOT="${__ENVSCP_OUTER_TESTROOT:-}"
    else
      unset TESTROOT
      echo "envscope: removed TESTROOT" >&2
    fi
  fi
  if [[ "${LOCALVAR:-}" == "${__ENVSCP_LAST_LOCALVAR:-}" ]]; then
    if [[ ${__ENVSCP_OUTERHAD_LOCALVAR:-0} -eq 1 ]]; then
      export LOCALVAR="${__ENVSCP_OUTER_LOCALVAR:-}"
    else
      unset LOCALVAR
      echo "envscope: removed LOCALVAR" >&2
    fi
  fi
  if [[ "${DATE_VAR:-}" == "${__ENVSCP_LAST_DATE_VAR:-}" ]]; then
    if [[ ${__ENVSCP_OUTERHAD_DATE_VAR:-0} -eq 1 ]]; then
      export DATE_VAR="${__ENVSCP_OUTER_DATE_VAR:-}"
    else
      unset DATE_VAR
      echo "envscope: removed DATE_VAR" >&2
    fi
  fi
  if [[ "${DATE_VAR_CACHED:-}" == "${__ENVSCP_LAST_DATE_VAR_CACHED:-}" ]]; then
    if [[ ${__ENVSCP_OUTERHAD_DATE_VAR_CACHED:-0} -eq 1 ]]; then
      export DATE_VAR_CACHED="${__ENVSCP_OUTER_DATE_VAR_CACHED:-}"
    else
      unset DATE_VAR_CACHED
      echo "envscope: removed DATE_VAR_CACHED" >&2
    fi
  fi
  if [[ "${QUOTED_VAR:-}" == "${__ENVSCP_LAST_QUOTED_VAR:-}" ]]; then
    if [[ ${__ENVSCP_OUTERHAD_QUOTED_VAR:-0} -eq 1 ]]; then
      export QUOTED_VAR="${__ENVSCP_OUTER_QUOTED_VAR:-}"
    else
      unset QUOTED_VAR
      echo "envscope: removed QUOTED_VAR" >&2
    fi
  fi
  if [[ "${SPACED_VAR:-}" == "${__ENVSCP_LAST_SPACED_VAR:-}" ]]; then
    if [[ ${__ENVSCP_OUTERHAD_SPACED_VAR:-0} -eq 1 ]]; then
      export SPACED_VAR="${__ENVSCP_OUTER_SPACED_VAR:-}"
    else
      unset SPACED_VAR
      echo "envscope: removed SPACED_VAR" >&2
    fi
  fi
  if [[ "${TILDE_VAR:-}" == "${__ENVSCP_LAST_TILDE_VAR:-}" ]]; then
    if [[ ${__ENVSCP_OUTERHAD_TILDE_VAR:-0} -eq 1 ]]; then
      export TILDE_VAR="${__ENVSCP_OUTER_TILDE_VAR:-}"
    else
      unset TILDE_VAR
      echo "envscope: removed TILDE_VAR" >&2
    fi
  fi
  if [[ "${TILDE_VAR_EXACT:-}" == "${__ENVSCP_LAST_TILDE_VAR_EXACT:-}" ]]; then
    if [[ ${__ENVSCP_OUTERHAD_TILDE_VAR_EXACT:-0} -eq 1 ]]; then
      export TILDE_VAR_EXACT="${__ENVSCP_OUTER_TILDE_VAR_EXACT:-}"
    else
      unset TILDE_VAR_EXACT
      echo "envscope: removed TILDE_VAR_EXACT" >&2
    fi
  fi
  if [[ "${TILDE_VAR_MID:-}" == "${__ENVSCP_LAST_TILDE_VAR_MID:-}" ]]; then
    if [[ ${__ENVSCP_OUTERHAD_TILDE_VAR_MID:-0} -eq 1 ]]; then
      export TILDE_VAR_MID="${__ENVSCP_OUTER_TILDE_VAR_MID:-}"
    else
      unset TILDE_VAR_MID
      echo "envscope: removed TILDE_VAR_MID" >&2
    fi
  fi
  if [[ "${TILDE_PATH_NOT_PATH:-}" == "${__ENVSCP_LAST_TILDE_PATH_NOT_PATH:-}" ]]; then
    if [[ ${__ENVSCP_OUTERHAD_TILDE_PATH_NOT_PATH:-0} -eq 1 ]]; then
      export TILDE_PATH_NOT_PATH="${__ENVSCP_OUTER_TILDE_PATH_NOT_PATH:-}"
    else
      unset TILDE_PATH_NOT_PATH
      echo "envscope: removed TILDE_PATH_NOT_PATH" >&2
    fi
  fi
  if [[ "${PATH:-}" == "${__ENVSCP_LAST_PATH:-}" ]]; then
    if [[ ${__ENVSCP_OUTERHAD_PATH:-0} -eq 1 ]]; then
      export PATH="${__ENVSCP_OUTER_PATH:-}"
    else
      unset PATH
      echo "envscope: removed PATH" >&2
    fi
  fi
  if [[ "${ROOT_VAR:-}" == "${__ENVSCP_LAST_ROOT_VAR:-}" ]]; then
    if [[ ${__ENVSCP_OUTERHAD_ROOT_VAR:-0} -eq 1 ]]; then
      export ROOT_VAR="${__ENVSCP_OUTER_ROOT_VAR:-}"
    else
      unset ROOT_VAR
      echo "envscope: removed ROOT_VAR" >&2
    fi
  fi
}

declare -A __ENVSCP_PARENT=(
  [zone_2]="zone_1"
  [zone_3]="zone_1"
  [zone_4]="zone_2"
)

__envscope_apply_one_zone() {
  local zone="$1"
  case "$zone" in
    zone_0)
      export ROOT_VAR='root-zone'
      echo "envscope: added ROOT_VAR" >&2
      ;;
    zone_1)
      export TESTROOT='testroot-value'
      echo "envscope: added TESTROOT" >&2
      export LOCALVAR='test'
      echo "envscope: added LOCALVAR" >&2
      export DATE_VAR=$(eval 'echo $RANDOM')
      echo "envscope: added DATE_VAR" >&2
      if [[ -z "${__ENVSCP_CACHE_zone_1_DATE_VAR_CACHED:-}" ]]; then
        __ENVSCP_CACHE_zone_1_DATE_VAR_CACHED=$(eval 'echo $RANDOM')
      fi
      export DATE_VAR_CACHED="${__ENVSCP_CACHE_zone_1_DATE_VAR_CACHED}"
      echo "envscope: added DATE_VAR_CACHED" >&2
      export QUOTED_VAR='val'\''withquote'
      echo "envscope: added QUOTED_VAR" >&2
      export SPACED_VAR='val  spaced'
      echo "envscope: added SPACED_VAR" >&2
      export TILDE_VAR='/home/user/foo'
      echo "envscope: added TILDE_VAR" >&2
      export TILDE_VAR_EXACT='/home/foo'
      echo "envscope: added TILDE_VAR_EXACT" >&2
      export TILDE_VAR_MID='a~/foo'
      echo "envscope: added TILDE_VAR_MID" >&2
      export TILDE_PATH_NOT_PATH=':/bin:~/foo'
      echo "envscope: added TILDE_PATH_NOT_PATH" >&2
      ;;
    zone_2)
      export PATH='/home/user/prefix-that-does-not-exist':"${PATH:-}"
      echo "envscope: added PATH" >&2
      export TESTROOT='now-with-prefix-'"${TESTROOT:-}"
      echo "envscope: added TESTROOT" >&2
      export LOCALVAR='test-foo'
      echo "envscope: added LOCALVAR" >&2
      ;;
    zone_3)
      export PATH='/home/user/bin:/usr/bin:/home/user/local/bin:/home/foo'
      echo "envscope: added PATH" >&2
      ;;
    zone_4)
      export LOCALVAR='test-foo-bar'
      echo "envscope: added LOCALVAR" >&2
      ;;
  esac
}

__envscope_apply_stack() {
  local zone_id="$1"
  local stack=()
  while [[ -n "$zone_id" && "$zone_id" != "NONE" ]]; do
    stack=("$zone_id" "${stack[@]}")
    zone_id="${__ENVSCP_PARENT[$zone_id]:-NONE}"
  done
  for z in "${stack[@]}"; do
    __envscope_apply_one_zone "$z"
  done
}

__envscope_hook() {
  local target_zone="NONE"
  case "$PWD" in
    "/home/user/test/foo/bar" | "/home/user/test/foo/bar/"* ) target_zone="zone_4" ;;
    "/home/user/test/tilde" | "/home/user/test/tilde/"* ) target_zone="zone_3" ;;
    "/home/user/test/foo" | "/home/user/test/foo/"* ) target_zone="zone_2" ;;
    "/home/user/test" | "/home/user/test/"* ) target_zone="zone_1" ;;
    "/" | "//"* ) target_zone="zone_0" ;;
  esac

  if [[ "$target_zone" != "${__ENVSCP_ZONE:-NONE}" ]]; then
    if [[ "${__ENVSCP_ZONE:-NONE}" != "NONE" ]]; then
      __envscope_restore_outer
    fi
    if [[ "$target_zone" != "NONE" ]]; then
      if [[ "${__ENVSCP_ZONE:-NONE}" == "NONE" ]]; then
        __envscope_save_outer
      fi
      __envscope_apply_stack "$target_zone"
  __ENVSCP_LAST_TESTROOT="${TESTROOT:-}"
  __ENVSCP_LAST_LOCALVAR="${LOCALVAR:-}"
  __ENVSCP_LAST_DATE_VAR="${DATE_VAR:-}"
  __ENVSCP_LAST_DATE_VAR_CACHED="${DATE_VAR_CACHED:-}"
  __ENVSCP_LAST_QUOTED_VAR="${QUOTED_VAR:-}"
  __ENVSCP_LAST_SPACED_VAR="${SPACED_VAR:-}"
  __ENVSCP_LAST_TILDE_VAR="${TILDE_VAR:-}"
  __ENVSCP_LAST_TILDE_VAR_EXACT="${TILDE_VAR_EXACT:-}"
  __ENVSCP_LAST_TILDE_VAR_MID="${TILDE_VAR_MID:-}"
  __ENVSCP_LAST_TILDE_PATH_NOT_PATH="${TILDE_PATH_NOT_PATH:-}"
  __ENVSCP_LAST_PATH="${PATH:-}"
  __ENVSCP_LAST_ROOT_VAR="${ROOT_VAR:-}"

    fi
    __ENVSCP_ZONE="$target_zone"
  fi
}

# Attach to PROMPT_COMMAND using '|| true' to bypass 'set -e' if declare fails.
if [[ ! "${PROMPT_COMMAND:-}" =~ __envscope_hook ]] && [[ "${PROMPT_COMMAND[*]:-}" != *__envscope_hook* ]]; then
  if [[ "$(declare -p PROMPT_COMMAND 2>/dev/null || true)" =~ "declare -a" ]]; then
    PROMPT_COMMAND+=("__envscope_hook")
  else
    PROMPT_COMMAND="${PROMPT_COMMAND:+${PROMPT_COMMAND}; }__envscope_hook"
  fi
fi
