# Copyright 2026 Stanislav Senotrusov
#
# This work is dual-licensed under the Apache License, Version 2.0
# and the MIT License. Refer to the LICENSE file in the top-level directory
# for the full license terms.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

# Set the project name
project := "envscope"

# Release module
mod release

# List all available recipes
# This helper recipe itself is hidden from the list
_default:
  @just --list
  @just --list release

# Build and install the binary to /usr/local/bin
install: build
  sudo install --compare --mode 0755 --owner root --group root --target-directory /usr/local/bin bin/{{project}}

# Build the binary for the current OS/Arch
build:
  CGO_ENABLED=0 go build -trimpath -ldflags="-s -w -X main.Version={{`just release version`}}" -o bin/{{project}} ./cmd/{{project}}

# Remove all build artifacts
clean:
  rm -rf bin/{{project}}

# Format project files
format:
  mdformat --number *.md
  rg "[^\x00-\x7F]" && true

# Output key project file paths for LLM prompt context
context:
  #!/usr/bin/env bash
  set -euo pipefail
  echo '$ just test'
  printf "%s\n" \
    cmd/{{project}}/*.go \
    test/* \
    go.mod \
    justfile \
    README.md

# Run the test suite
test: build
  #!/usr/bin/env bash
  set -euo pipefail
  bash test/integration.bash
  bash test/integration-home.bash

  generate() {
    echo "# NOTE: This is an autogenerated file intended for use as LLM/AI context and for preserving program output state for future reference. Do NOT include its contents in generated output."
    bin/envscope -c test/test.conf "$@" | sed "s|${HOME}/|/home/user/|g"
  }

  generate hook bash > test/hook.bash
  generate -reportvars hook bash > test/hook-reportnames.bash

# Start a nested Bash shell with the test configuration hook pre-loaded
test-shell: build
  #!/usr/bin/env bash
  set -euo pipefail
  export HOME="$(pwd)/test"
  bash --rcfile <(
    echo 'export PS1="${PS1}(envscope-test) "'
    bin/envscope -c test/test.conf -reportvars hook bash
    echo 'cd $HOME'
  ) -i || true

# Run shell performance benchmarks
shell-benchmarks:
  bash benchmarks/var-indirection.bash
  fish benchmarks/var-indirection.fish
  zsh  benchmarks/var-indirection.zsh
  bash benchmarks/var-access.bash
  zsh  benchmarks/var-access.zsh
